version: 2

registries:
  github-fluidtruck:
    type: git
    url: https://github.com
    username: x-access-token
    password: ${{ secrets.DEVBOT_GITHUB_TOKEN }}

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    labels:
      - "dependabot"
      - "docker"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    labels:
      - "dependabot"
      - "actions"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    registries: "*"
    labels:
      - "dependabot"
      - "go"
