repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.
  name: deepcopy
  description: The deepcopy library.
  homepage: https://deepcopy.fluidtruck.io
  default_branch: main

  has_issues: false
  has_wiki: false
  has_downloads: false

  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_auto_merge: false
  delete_branch_on_merge: true

collaborators:
  - username: fluid-devbot
    permission: admin

teams:
  - name: security
    permission: admin
  - name: devops
    permission: admin
  - name: qa
    permission: pull
  - name: backend
    permission: push

branches:
  - name: main
    protection:
      enforce_admins: false
      required_linear_history: true
      required_signatures: false
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
      required_status_checks:
        strict: false
        contexts:
          - lint
          - test
          - boost-security-scan
          - Semantic Pull Request
      restrictions:
        users:
          - fluid-devbot
        teams:
          - devops
          - security
          - backend
