name: deploy

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
      - v[0-9]+.[0-9]+.[0-9]+-*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Previous Runs
        uses: ahmadnassri/action-workflow-queue@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          echo "Release process TBD"
